name: Middleware NodeJS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./middleware

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

  - name: Use mock configuration
    run: |
      cp ./config/__mocks__/LocalEnvConfig.js ./config/LocalEnvConfig.js
        
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

# middleware tests
    - name: install middleware dependencies
      run: npm ci
    
    - name: Run middleware jest tests
      run: npm run test