name: middleware nodejs CI

on:
  push:
    branches: [ MiddlewareUnitTests ]
  pull_request:
    branches: [ MiddlewareUnitTests ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./middleware

    strategy:
      matrix:
        node-version: [18.x]
        
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

# middleware tests
      - name: Run middleware tests
        run: npm run test